manifest:
  remotes:
    - name: lucamezzatesta
      url-base: https://github.com/lucamezzatesta
  projects:
    - name: zmk
      remote: lucamezzatesta
      revision: main
      import: app/west.yml
  self:
    path: config
