name: Automerge

on:
  pull_request:
    branches:
      - "main"
      - "develop"

    pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: 'pascalgn/automerge-action@v0.15.6'
        env:
          GITHUB_TOKEN: '${{ secrets.RELEASE_TOKEN }}'
          MERGE_LABELS: ''
          MERGE_FILTER_AUTHOR: "cloverdefa"